language: c

cache: ccache

sudo: required 
dist: trusty

script:
- sudo apt-get install yasm libxrandr-dev libx11-dev libxi-dev libxinerama-dev
- ccache -s
- chmod +x build.sh
- ./build.sh

after_script:
- ccache -s

