language: c

cache: ccache

sudo: false 
dist: trusty

addons:
  apt:
    packages:
    - yasm
    - libxrandr-dev
    - libx11-dev
    - libxi-dev
    - libxinerama-dev
    - libxcursor-dev

script:
#- sudo apt-get install yasm libxrandr-dev libx11-dev libxi-dev libxinerama-dev libxcursor-dev
- ccache --max-size==2.0G
- ccache -s
- chmod +x build.sh
- timeout 40m ./build.sh 

after_script:
- ccache -s
