language: c

cache: ccache

sudo: required 
dist: trusty

script:
- which yasm
- sudo apt-get remove yasm
- which yasm
- sudo apt-get install nasm
- ccache -s
- chmod +x build.sh
- ./build.sh

after_script:
- ccache -s

